services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        UID: 1000
        GID: 1000
    # user: 1000:1000
    volumes:
      - ./src:/var/www/html
    ports:
      - "50080:80"
